scalaVersion := "2.11.8"

libraryDependencies += "org.xerial" % "sqlite-jdbc" % "3.15.1"
libraryDependencies += "com.typesafe" % "config" % "1.3.1"
libraryDependencies += "org.liquibase" % "liquibase-core" % "3.5.3"
libraryDependencies += "org.jbehave" % "jbehave-scala" % "4.1"
libraryDependencies += "org.scalactic" %% "scalactic" % "3.0.1"
libraryDependencies += "org.scalatest" %% "scalatest" % "3.0.1" % "test"
libraryDependencies += "ch.qos.logback" % "logback-classic" % "1.1.7"
libraryDependencies += "com.typesafe.scala-logging" %% "scala-logging" % "3.5.0"

//libraryDependencies += "org.seleniumhq.selenium" % "selenium-java" % "3.0.1"
libraryDependencies += "org.seleniumhq.selenium" % "selenium-api" % "3.0.1"
libraryDependencies += "org.seleniumhq.selenium" % "selenium-support" % "3.0.1"
libraryDependencies += "org.seleniumhq.selenium" % "selenium-firefox-driver" % "3.0.1"